azepug/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from users import views as users_views

urlpatterns = [
    path('blogs/', include('blog.urls')),
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('register/', include('users.urls')),
    path('login/',auth_views.LoginView.as_view(template_name = 'users/login.html'), name = "login"),
    path('logout/',auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = "logout"),
    path('profile/', users_views.profile, name = 'profile'),
    path('edit/', users_views.edit_profile_view, name = 'edit_profile'),
    path('vacancies/', include('vacancy.urls'), name = 'vacancy'),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from .views import PostListView, post_detail, PostCreateView, PostUpdateView, PostDeleteView
app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),

    path('post/<int:pk>/',
    post_detail , name='about_post'),

    path('new/', PostCreateView.as_view(), name='create_post'),

    path('post/<int:pk>/update/',
    PostUpdateView.as_view(), name='update_post'),

    path('post/<int:pk>/remove/',
    PostDeleteView.as_view(), name='delete_post'),
]

blog/models.py
from django.db import models as m
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse


class PublishedManager(m.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status = 'Published')

class Tags(m.Model):
    tag = m.CharField('tag',max_length=20)
    

class Category(m.Model):
    name_of_category = m.CharField('Kateqoriya', max_length= 30)

    def __str__(self):
        return self.name_of_category
    class Meta:
        verbose_name = "Kateqoriya"
        verbose_name_plural = "Kateqoriyalar"

    class Meta:
        verbose_name = 'Kateqoriya'
        verbose_name_plural = 'Kateqoriyalar'

class Post(m.Model):
    category = m.ForeignKey(Category, null =True, on_delete=m.SET_NULL)
    title = m.CharField("Başlıq", max_length=20)
    content = m.TextField()
    author = m.ForeignKey(User, on_delete=m.CASCADE)
    date_created = m.DateTimeField(default= timezone.now)
    STATUS_CHOICES = (
        ('Draft', 'draft'),
        ('Published', 'published'))

    status = m.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    def get_absolute_url(self):
        return reverse('blog:about_post', kwargs = {'pk': self.pk})
        
    #-------------- Managers --------------------------
    objects = m.Manager()
    published = PublishedManager()
    """
        published - Query set manager where all objects is 'posts with published status. 
        at: class PublishedManager'

    """

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name, verbose_name_plural = "Post", "Postlar"


# this comment model uses in blog, vacancy.. to_item -> post for blog, vacancy for vacancy app
class Comment(m.Model):
    author = m.ForeignKey(User,verbose_name='müəllif', related_name = 'comments', null = True, on_delete=m.SET_NULL)
    post = m.ForeignKey(Post, related_name = 'comments', on_delete = m.CASCADE, null=True)
    vacancy = m.ForeignKey('vacancy.Vacancy', related_name='comments', on_delete=m.CASCADE, null = True)
    email = m.EmailField('Elektron poçt')
    body = m.TextField('Şərh')
    created = m.DateTimeField('Yaradılma tarixi',auto_now_add = True)
    updated = m.DateTimeField('Yenilənmə tariix', auto_now = True)
    active = m.BooleanField('Aktiv', default = True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
         return f'Comment to -- " by {self.author} on: {self.created}'

blog/forms.py
from django import forms
from .models import Comment

class UserCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

class GuestCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['email', 'body']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
# from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView,CreateView, DeleteView, UpdateView

from.models import Post
from .forms import GuestCommentForm, UserCommentForm

#------------------- show post -------------


class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    paginate_by = 4
    context_object_name = 'posts'
    ordering = ['-date_created']



def post_detail(request, pk):
    # check user and select kind of comment form
    if request.user.is_authenticated:
        CommentForm = UserCommentForm
    else:
        CommentForm = GuestCommentForm

    post = get_object_or_404(Post, id = pk)
    comments = post.comments.filter(active = True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data = request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit = False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, 'blog/about_post.html', {'post':post,
     'comments':comments, 'new_comment':new_comment, 'comment_form':comment_form})



class PostCreateView(LoginRequiredMixin,CreateView):
    model=Post
    fields = ['title', 'category', 'content']
    template_name = 'blog/CRUD_post/create_post.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin,UserPassesTestMixin, UpdateView):
    model=Post
    fields = ['title', 'category', 'content']
    template_name = 'blog/CRUD_post/create_post.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        else: return False

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin ,DeleteView):
    model = Post
    template_name = 'blog/CRUD_post/delete_post.html'
    success_url = '/blogs'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        else: return False

blog/templates/blog/about_post.html
{% extends 'blog/post_list.html'%}
{% block title %} {{post.title}} - AzePUG {% endblock %}
{% block body%}
<div class="container">
    <h2><i>{{post.title}}</i></h2>
    <p class="text-lg-right"> <i>Müəllif: <a href="#">{{post.author}}</a> Tarix:{{post.date_created}}</i></p>
    <div class="text-sm-center">
        {{post.content}}
        <br>
        {% if request.user == post.author %}
            <a class = "btn btn-secondary" href="{% url 'blog:update_post' post.id %}" >
                Redaktə et
            </a>

            <a class = "btn btn-secondary" href="{% url 'blog:delete_post' post.id %}" >
                Sil
            </a>
        {% endif %}
    </div>
        {% with comments.count as total_comments %}
        <h4>
            Cəmi {{total_comments}} şərh
        </h4>
    {% endwith %}
    {% for comment in comments %}
        <div class="card">
            <p class="info">
                Şərh  {{forloop.counter}} < - {{comment.name_author}}
                {{comment.created}}
            </p>
            {{comment.body|linebreaks}}
        </div>
    {% empty %}
        <h4>İlk şərhçi siz olun! </h4>
    {% endfor %}

{% if new_comment %}
    <small class="text-success">Şərhiniz uğurla əlavə edildi</small>
{% else %}
    <h3>Yeni şərh əlavə et</h3>
    <form method="POST">
{% if user.is_authenticated %}
<!--        decorate here, for loginned user comment -->
    {{comment_form.as_p}}
{% else %}
<!--        it is for non auth user-->
    {{comment_form.as_p}}
{% endif %}
    {% csrf_token %}
    <p>
        <input class="btn btn-success" type="submit" value="Əlavə et">
    </p>
    </form>
{% endif %}
</div>
{% endblock %}

blog/templates/blog/base.html
{% load static% }
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>

</body>
</html>

blog/templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous%}
            <a class = "btn btn-dark btn-sm mb-10px" href="?page={{page.previous_page_number}}"> <<< </a>
        {% endif %}
        <span class="current btn-group-lg text-lg-right">
            {{page.number}} --- {{page.paginator.num_pages}}
        </span>
        {% if page.has_next %}
            <a class = "btn btn-dark btn-sm mb-10px" href="?page={{page.next_page_number}}"> >>> </a>
        {% endif %}
    </span>
</div>

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}
                       <!-- Head Block -->
{% block head %} 
<link rel="stylesheet" href="{% static 'blog/main.css'%}">
{% endblock %}
                           <!-- Title -->
{% block title %} Məqalələr - azepug{% endblock %} 
                          <!-- Content -->
{% block body %}
<div class="container">
    <div class="blog-list">
        <div class="row">
            <div class="col-md-12">
                <h2> Məqalələr</h2>
                {% if user.is_authenticated %}
                    <div>
                        <a class = "btn btn-secondary" href="{% url 'blog:create_post' %}">
                            Post əlavə et
                        </a>
                    </div>
                {% endif %}
               
            </div>
        </div>

        {% for post in posts%}
        <div class = "card">
            <a href="{% url 'blog:about_post' post.id %}"> <h3> {{post.title}}</h3></a>
            <div class = "card-subtitle">
                <i> Paylaşdı: <a href="#"> <strong>{{post.author}}</strong></a> Tarix:  {{post.date_created}} </i>
            </div>
            <p>{{post.content|truncatewords:30|linebreaks}}</p>
        </div>

        {% endfor %}
    </div>
</div>
{% include 'blog/pagination.html' with page=page_obj %}
{% endblock %}