azepug/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from users import views as users_views

urlpatterns = [
    path('blogs/', include('blog.urls')),
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('register/', include('users.urls')),
    path('login/',auth_views.LoginView.as_view(template_name = 'users/login.html'), name = "login"),
    path('logout/',auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = "logout"),
    path('profile/', users_views.profile, name = 'profile'),
    path('edit/', users_views.edit_profile_view, name = 'edit_profile'),
    path('vacancies/', include('vacancy.urls'), name = 'vacancy'),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from .views import PostListView, post_detail, PostCreateView, PostUpdateView, PostDeleteView
app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),

    path('post/<int:pk>/',
    post_detail , name='about_post'),

    path('new/', PostCreateView.as_view(), name='create_post'),

    path('post/<int:pk>/update/',
    PostUpdateView.as_view(), name='update_post'),

    path('post/<int:pk>/remove/',
    PostDeleteView.as_view(), name='delete_post'),
]

vacancy/urls.py
from django.urls import path
from .views import (VacancyListView, VacancyCreateView,
                    VacancyDeleteView,VacancyUpdateView, vacancy_detail
)
app_name = 'vacancy'

urlpatterns = [
    path('', VacancyListView.as_view(), name='vacancy_list'),

    path('vacancy/<int:pk>/',
    vacancy_detail, name='about_vacancy'),

    path('new/', VacancyCreateView.as_view(), name='create_vacancy'),

    path('post/<int:pk>/update/',
    VacancyUpdateView.as_view(), name='update_vacancy'),

    path('post/<int:pk>/remove/',
    VacancyDeleteView.as_view(), name='delete_vacancy'),
]

vacancy/models.py
from django.db import models as m
from django.contrib.auth.models import User
from django.urls import reverse


class Vacancy(m.Model):
    author = m.ForeignKey(User, on_delete=m.CASCADE)
    title = m.CharField('Bashliq', max_length = 50)
    content = m.TextField('Vakansiya')
    dead_line = m.DateField("Bitmə tarixi (YYYY-MM-DD)", null=True)
    date_created = m.DateField("Yaradılma tarixi", auto_now_add=True)
    freelance = m.BooleanField("Freelance imkanı")


    def get_absolute_url(self):
        return reverse('vacancy:about_vacancy', kwargs = {'pk': self.pk})

    class Meta:
        verbose_name = 'Vakansiya'
        verbose_name_plural = 'Vakansiyalar'
    def __str__(self):
        return f'{self.title} - {self.author}'

vacancy/forms.py
from blog.forms import GuestCommentForm as GForm
from blog.forms import UserCommentForm as UForm
from .models import Comment

class UserCommentForm(UForm):
    class Meta:
        model = Comment

class GuestCommentForm(GForm):
    class Meta:
        model = Comment

vacancy/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from .models import Vacancy
from blog.forms import GuestCommentForm, UserCommentForm


class VacancyListView(ListView):
    model = Vacancy
    template_name = 'vacancy/vacancy_list.html'
    paginate_by = 5
    context_object_name = 'vacancies'
    ordering = ['-date_created']

def vacancy_detail(request, pk):
    # check user and select kind of comment form
    if request.user.is_authenticated:
        CommentForm = UserCommentForm
    else:
        CommentForm = GuestCommentForm
    vacancy = get_object_or_404(Vacancy, id = pk)
    comments = vacancy.comments.filter(active = True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data = request.POST)
        print('-'*50)
        print(request.POST)
        print('-'*50)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit = False)
            new_comment.vacancy = vacancy
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, 'vacancy/about_vacancy.html', {'vacancy':vacancy,
     'comments':comments, 'new_comment':new_comment, 'comment_form':comment_form})



class VacancyCreateView(LoginRequiredMixin,CreateView):
    model=Vacancy
    fields = ['title', 'content', 'dead_line', 'freelance']
    template_name = 'vacancy/CRUD_vacancy/create_vacancy.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class VacancyUpdateView(LoginRequiredMixin,UserPassesTestMixin, UpdateView):
    model=Vacancy
    fields = ['title', 'content', 'dead_line', 'freelance']
    template_name = 'vacancy/CRUD_vacancy/create_vacancy.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        vacancy = self.get_object()
        if self.request.user == vacancy.author:
            return True
        else: return False

class VacancyDeleteView(LoginRequiredMixin, UserPassesTestMixin ,DeleteView):
    model = Vacancy
    template_name = 'vacancy/CRUD_vacancy/delete_vacancy.html'
    success_url = '/vacancies'

    def test_func(self):
        vacancy = self.get_object()
        if self.request.user == vacancy.author:
            return True
        else: return False

vacancy/templates/vacancy/about_vacancy.html
{% extends 'base.html'%}
{% block title %} {{vacancy.title}} {% endblock %}
{% block body%}
<div class="container">
    <h2><i>{{vacancy.title}}</i></h2>
    <p class="text-lg-right"> <i>Müəllif: <a href="#">{{vacancy.author}}</a> Tarix:{{vacancy.date_created}}</i></p>
    <div class="text-sm-center">
        {{vacancy.content}}
        <br>
        <ul>
            <li>Bitmə tarixi: {{vacancy.dead_line}}</li>
            {% if vacancy.freelance %}
                <li>Freelance: Hə</li>
            {% else %}
                <li>Freelance: Yox</li>
            {% endif %}
        </ul>
        <br>
        {% if request.user == vacancy.author %}
            <a class = "btn btn-secondary" href="{% url 'vacancy:update_vacancy' vacancy.id %}" >
                Redaktə et
            </a>

            <a class = "btn btn-secondary" href="{% url 'vacancy:delete_vacancy' vacancy.id %}" >
                Sil
            </a>
        {% endif %}
    </div>
    {% with comments.count as total_comments %}
        <h3>
            Cəmi {{total_comments}} şərh
        </h3>
    {% endwith %}
    {% for comment in comments %}
        <div class="card">
            <p class="info">
                Comment {{forloop.counter}} by {{comment.name_author}}
                {{comment.created}}
            </p>
            {{comment.body|linebreaks}}
        </div>
    {% empty %}
        <p>İlk şərhçi siz olun! </p>
    {% endfor %}

{% if new_comment %}
    <small class="text-success">Şərhiniz uğurla əlavə edildi</small>
{% else %}
    <h4>Yeni şərh əlavə et</h4>
    <form method="POST"> 
    {{comment_form.as_p}}
    {% csrf_token %}
    <p>
        <input type="submit" value="Əlavə et">
    </p>
    </form>
{% endif %}

</div>
{% endblock %}

vacancy/templates/vacancy/base.html
{% extends 'base.html' %}

vacancy/templates/vacancy/vacancy_list.html
{% extends 'base.html' %}
{% block title %} Vakansiyalar - AzePUG{% endblock %}
{% block head%} {% endblock %}
{% block body %}
    <div class = "container">
        <h2>
            Vakansiyalar
        </h2>
        <div class="mb-4">
            <a class = "btn btn-secondary" href="{% url 'vacancy:create_vacancy' %}">
                Vakansiya əlavə et
            </a>
        </div>
        {% for v in vacancies %}
            <div class = "card mb-10">
                <div class="card card-title">
                    <a class="card-link" href="{% url 'vacancy:about_vacancy' v.id %}">
                      <h3> {{v.title}} </h3>
                    </a>
                </div>
                <div class="car-body">
                    {{v.content|truncatewords:30|linebreaks}}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}